// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ScoreSystemClientProgram;

impl ScoreSystemClientProgram {
    pub const ROUTE_ID_SCORE: u8 = 1;
}

impl sails_rs::client::Program for ScoreSystemClientProgram {}

pub trait ScoreSystemClient {
    type Env: sails_rs::client::GearEnv;
    fn score(&self) -> sails_rs::client::Service<score::ScoreImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> ScoreSystemClient
    for sails_rs::client::Actor<ScoreSystemClientProgram, E>
{
    type Env = E;
    fn score(&self) -> sails_rs::client::Service<score::ScoreImpl, Self::Env> {
        self.service(ScoreSystemClientProgram::ROUTE_ID_SCORE)
    }
}
pub trait ScoreSystemClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        initial_attesters: Vec<ActorId>,
    ) -> sails_rs::client::PendingCtor<ScoreSystemClientProgram, io::New, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> ScoreSystemClientCtors
    for sails_rs::client::Deployment<ScoreSystemClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        initial_attesters: Vec<ActorId>,
    ) -> sails_rs::client::PendingCtor<ScoreSystemClientProgram, io::New, Self::Env> {
        self.pending_ctor((initial_attesters,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (initial_attesters: Vec<ActorId>) -> (), 0);
}

pub mod score {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct RecordScoreReq {
        pub actor: ActorId,
        pub dimensions: ScoreDimensions,
        pub confidence: u8,
        pub evidence_hash: [u8; 32],
        pub reason_code: String,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ScoreConfig {
        pub owner: ActorId,
        pub score_attesters: Vec<ActorId>,
        pub formula_version: u32,
        pub next_score_id: u64,
        pub paused: bool,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ScoreDimensions {
        pub proposal_quality: u8,
        pub delivery_reliability: u8,
        pub integration_count: u8,
        pub past_impact_score: u8,
        pub community_signal: u8,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum ScoreError {
        Unauthorized,
        Paused,
        InvalidActor,
        InvalidDimension,
        InvalidConfidence,
        InvalidEvidenceHash,
        EmptyReasonCode,
        ReasonCodeTooLong,
        LimitTooLarge,
        ScoreIdOverflow,
        InvalidFormulaVersion,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ScoreHistoryPage {
        pub items: Vec<ScoreSnapshot>,
        pub next_cursor: Option<u64>,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ScoreSnapshot {
        pub id: u64,
        pub actor: ActorId,
        pub dimensions: ScoreDimensions,
        pub overall: u8,
        pub confidence: u8,
        pub evidence_hash: [u8; 32],
        pub reason_code: String,
        pub formula_version: u32,
        pub attester: ActorId,
        pub recorded_at: u64,
    }

    pub trait Score {
        type Env: sails_rs::client::GearEnv;
        fn add_score_attester(
            &mut self,
            attester: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddScoreAttester, Self::Env>;
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
        fn get_score(
            &self,
            actor: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetScore, Self::Env>;
        fn get_score_history(
            &self,
            actor: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetScoreHistory, Self::Env>;
        fn get_score_snapshot(
            &self,
            actor: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetScoreSnapshot, Self::Env>;
        fn list_score_attesters(
            &self,
        ) -> sails_rs::client::PendingCall<io::ListScoreAttesters, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn record_score(
            &mut self,
            req: RecordScoreReq,
        ) -> sails_rs::client::PendingCall<io::RecordScore, Self::Env>;
        fn remove_score_attester(
            &mut self,
            attester: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveScoreAttester, Self::Env>;
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env>;
        fn update_formula_version(
            &mut self,
            new_version: u32,
        ) -> sails_rs::client::PendingCall<io::UpdateFormulaVersion, Self::Env>;
    }

    pub struct ScoreImpl;

    impl sails_rs::client::Identifiable for ScoreImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([46, 77, 218, 189, 211, 198, 40, 248]);
    }

    impl<E: sails_rs::client::GearEnv> Score for sails_rs::client::Service<ScoreImpl, E> {
        type Env = E;
        fn add_score_attester(
            &mut self,
            attester: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddScoreAttester, Self::Env> {
            self.pending_call((attester,))
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_score(
            &self,
            actor: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetScore, Self::Env> {
            self.pending_call((actor,))
        }
        fn get_score_history(
            &self,
            actor: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetScoreHistory, Self::Env> {
            self.pending_call((actor, cursor, limit))
        }
        fn get_score_snapshot(
            &self,
            actor: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetScoreSnapshot, Self::Env> {
            self.pending_call((actor,))
        }
        fn list_score_attesters(
            &self,
        ) -> sails_rs::client::PendingCall<io::ListScoreAttesters, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn record_score(
            &mut self,
            req: RecordScoreReq,
        ) -> sails_rs::client::PendingCall<io::RecordScore, Self::Env> {
            self.pending_call((req,))
        }
        fn remove_score_attester(
            &mut self,
            attester: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveScoreAttester, Self::Env> {
            self.pending_call((attester,))
        }
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env> {
            self.pending_call(())
        }
        fn update_formula_version(
            &mut self,
            new_version: u32,
        ) -> sails_rs::client::PendingCall<io::UpdateFormulaVersion, Self::Env> {
            self.pending_call((new_version,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddScoreAttester (attester: ActorId) -> super::Result<(), super::ScoreError, >, 0, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetConfig () -> super::ScoreConfig, 1, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetScore (actor: ActorId) -> super::Option<super::ScoreSnapshot, >, 2, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetScoreHistory (actor: ActorId, cursor: super::Option<u64, >, limit: u32) -> super::Result<super::ScoreHistoryPage, super::ScoreError, >, 3, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetScoreSnapshot (actor: ActorId) -> super::Option<super::ScoreSnapshot, >, 4, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListScoreAttesters () -> Vec<ActorId>, 5, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> super::Result<(), super::ScoreError, >, 6, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RecordScore (req: super::RecordScoreReq) -> super::Result<u64, super::ScoreError, >, 7, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RemoveScoreAttester (attester: ActorId) -> super::Result<(), super::ScoreError, >, 8, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unpause () -> super::Result<(), super::ScoreError, >, 9, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(UpdateFormulaVersion (new_version: u32) -> super::Result<(), super::ScoreError, >, 10, <super::ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum ScoreEvents {
            #[codec(index = 0)]
            FormulaVersionUpdated { old_version: u32, new_version: u32 },
            #[codec(index = 1)]
            Paused,
            #[codec(index = 2)]
            ScoreAttesterAdded { attester: ActorId },
            #[codec(index = 3)]
            ScoreAttesterRemoved { attester: ActorId },
            #[codec(index = 4)]
            ScoreRecorded {
                id: u64,
                actor: ActorId,
                dimensions: ScoreDimensions,
                overall: u8,
                confidence: u8,
                evidence_hash: [u8; 32],
                reason_code: String,
                formula_version: u32,
                attester: ActorId,
                recorded_at: u64,
            },
            #[codec(index = 5)]
            Unpaused,
        }

        impl ScoreEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::FormulaVersionUpdated { .. } => 0,
                    Self::Paused { .. } => 1,
                    Self::ScoreAttesterAdded { .. } => 2,
                    Self::ScoreAttesterRemoved { .. } => 3,
                    Self::ScoreRecorded { .. } => 4,
                    Self::Unpaused { .. } => 5,
                }
            }
        }

        impl sails_rs::client::Event for ScoreEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for ScoreEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <ScoreImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for ScoreImpl {
            type Event = ScoreEvents;
        }
    }
}
